name: First Workflow
on: workflow_dispatch   #manual trigger
jobs:
  first-job:   #any name (not a command)
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - bye!"
      # Running multi line shell commands:
      # run: |
          # echo "First output"
          # echo "Second output"        

  
